import type { BloomPalette } from "../components/theme/theme";

export const midnightGarden: BloomPalette = {
  name: "midnight",
  light: {
    "--bloom-font": "'Cormorant Garamond', serif",
    "--bloom-font-display": "'Playfair Display', serif",
    "--bloom-bg": "#F5F3F8",
    "--bloom-surface": "#EAE6F0",
    "--bloom-surface2": "#DBD5E4",
    "--bloom-text": "#1E1A28",
    "--bloom-text-secondary": "#6B6580",
    "--bloom-accent1": "#5E8C6A",
    "--bloom-accent1-deep": "#3D6B4A",
    "--bloom-accent2": "#6A7EC8",
    "--bloom-accent2-deep": "#4A5EA8",
    "--bloom-accent3": "#8B6AAE",
    "--bloom-accent3-deep": "#6A4A8E",
    "--bloom-accent4": "#C86A7E",
    "--bloom-accent4-deep": "#A84A5E",
    "--bloom-shadow": "0 2px 24px rgba(30,26,40,0.08)",
    "--bloom-shadow-hover": "0 8px 40px rgba(30,26,40,0.14)",
    "--bloom-radius-sm": "8px",
    "--bloom-radius": "12px",
    "--bloom-radius-lg": "16px",
    "--bloom-radius-pill": "999px",
  },
  dark: {
    "--bloom-font": "'Cormorant Garamond', serif",
    "--bloom-font-display": "'Playfair Display', serif",
    "--bloom-bg": "#0F1117",
    "--bloom-surface": "#1A1D27",
    "--bloom-surface2": "#252A36",
    "--bloom-text": "#E2E0EC",
    "--bloom-text-secondary": "#8B87A0",
    "--bloom-accent1": "#5E8C6A",
    "--bloom-accent1-deep": "#3D6B4A",
    "--bloom-accent2": "#6A7EC8",
    "--bloom-accent2-deep": "#4A5EA8",
    "--bloom-accent3": "#8B6AAE",
    "--bloom-accent3-deep": "#6A4A8E",
    "--bloom-accent4": "#C86A7E",
    "--bloom-accent4-deep": "#A84A5E",
    "--bloom-shadow": "0 2px 24px rgba(0,0,0,0.3)",
    "--bloom-shadow-hover": "0 8px 40px rgba(0,0,0,0.4)",
    "--bloom-radius-sm": "8px",
    "--bloom-radius": "12px",
    "--bloom-radius-lg": "16px",
    "--bloom-radius-pill": "999px",
  },
};

export const desertRose: BloomPalette = {
  name: "desert",
  light: {
    "--bloom-font": "'Karla', sans-serif",
    "--bloom-font-display": "'Lora', serif",
    "--bloom-bg": "#FBF5EE",
    "--bloom-surface": "#F2E8DA",
    "--bloom-surface2": "#E6D8C4",
    "--bloom-text": "#3D2E1E",
    "--bloom-text-secondary": "#8C7A66",
    "--bloom-accent1": "#B8A080",
    "--bloom-accent1-deep": "#96795A",
    "--bloom-accent2": "#D4956A",
    "--bloom-accent2-deep": "#B87040",
    "--bloom-accent3": "#C4887C",
    "--bloom-accent3-deep": "#A8685C",
    "--bloom-accent4": "#CC6B5E",
    "--bloom-accent4-deep": "#A84A3E",
    "--bloom-shadow": "0 2px 24px rgba(61,46,30,0.08)",
    "--bloom-shadow-hover": "0 8px 40px rgba(61,46,30,0.14)",
    "--bloom-radius-sm": "16px",
    "--bloom-radius": "20px",
    "--bloom-radius-lg": "28px",
    "--bloom-radius-pill": "999px",
  },
  dark: {
    "--bloom-font": "'Karla', sans-serif",
    "--bloom-font-display": "'Lora', serif",
    "--bloom-bg": "#1C1610",
    "--bloom-surface": "#28201A",
    "--bloom-surface2": "#362C22",
    "--bloom-text": "#E8DED0",
    "--bloom-text-secondary": "#9A8A76",
    "--bloom-accent1": "#A08868",
    "--bloom-accent1-deep": "#7E6848",
    "--bloom-accent2": "#C48050",
    "--bloom-accent2-deep": "#A06030",
    "--bloom-accent3": "#B07868",
    "--bloom-accent3-deep": "#905848",
    "--bloom-accent4": "#B85848",
    "--bloom-accent4-deep": "#983828",
    "--bloom-shadow": "0 2px 24px rgba(0,0,0,0.3)",
    "--bloom-shadow-hover": "0 8px 40px rgba(0,0,0,0.4)",
    "--bloom-radius-sm": "16px",
    "--bloom-radius": "20px",
    "--bloom-radius-lg": "28px",
    "--bloom-radius-pill": "999px",
  },
};

export const oceanMist: BloomPalette = {
  name: "ocean",
  light: {
    "--bloom-font": "'Nunito', sans-serif",
    "--bloom-font-display": "'Space Grotesk', sans-serif",
    "--bloom-bg": "#F4F8FA",
    "--bloom-surface": "#E8F0F4",
    "--bloom-surface2": "#D4E2EA",
    "--bloom-text": "#1A2E3A",
    "--bloom-text-secondary": "#5E7A8C",
    "--bloom-accent1": "#6AB8C4",
    "--bloom-accent1-deep": "#3A96A8",
    "--bloom-accent2": "#E0A860",
    "--bloom-accent2-deep": "#C08840",
    "--bloom-accent3": "#7CA0D4",
    "--bloom-accent3-deep": "#5A80B8",
    "--bloom-accent4": "#D47A7A",
    "--bloom-accent4-deep": "#B85A5A",
    "--bloom-shadow": "0 2px 24px rgba(26,46,58,0.06)",
    "--bloom-shadow-hover": "0 8px 40px rgba(26,46,58,0.1)",
    "--bloom-radius-sm": "6px",
    "--bloom-radius": "10px",
    "--bloom-radius-lg": "14px",
    "--bloom-radius-pill": "999px",
  },
  dark: {
    "--bloom-font": "'Nunito', sans-serif",
    "--bloom-font-display": "'Space Grotesk', sans-serif",
    "--bloom-bg": "#0E1A20",
    "--bloom-surface": "#162228",
    "--bloom-surface2": "#1E2E36",
    "--bloom-text": "#D8E8EE",
    "--bloom-text-secondary": "#7A9AAC",
    "--bloom-accent1": "#4A9AAC",
    "--bloom-accent1-deep": "#2A7A8C",
    "--bloom-accent2": "#C89048",
    "--bloom-accent2-deep": "#A87030",
    "--bloom-accent3": "#5A80B8",
    "--bloom-accent3-deep": "#3A60A0",
    "--bloom-accent4": "#B85A5A",
    "--bloom-accent4-deep": "#983A3A",
    "--bloom-shadow": "0 2px 24px rgba(0,0,0,0.3)",
    "--bloom-shadow-hover": "0 8px 40px rgba(0,0,0,0.4)",
    "--bloom-radius-sm": "6px",
    "--bloom-radius": "10px",
    "--bloom-radius-lg": "14px",
    "--bloom-radius-pill": "999px",
  },
};

export const builtInPalettes: BloomPalette[] = [midnightGarden, desertRose, oceanMist];
